### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by whyman** [haku/dlnatoad#13]
Just noticed there is no LICENSE file, might be nice to add one.

**Comment by matthiasblaesing** [comment]
I think it would not only be nice, but required. The moment anyone wants to distributes builds from this or build other work on it, it becomes a problem. Would be a shame as it would most probably fight for a use-case I though about.

**Comment by haku** [comment]
done.  not sure how this project got 10 years in before i got around to doing this?
tbh i am kinda surprised this thing is interesting/useful to anyone other than me since i have never promoted it or even tried to document it...
like how are people even finding this thing exists? 
and like the README is way out of date from all the stuff i have added over the years...
to the point where i am pondering renaming the project to deemphasise the DLNA part cos it does a bunch of other stuff now...

**Comment by matthiasblaesing** [comment]
Thank you!
